-- +migrate Up
-- ============================================================================
-- mcp-catalog-v1 :: mcp_servers
-- ============================================================================
-- First business table for octo-marketplace. Stores the MCP records browsed
-- and created through /market/api/v1/mcps.
--
-- Design notes (see .octospec/tasks/mcp-catalog-v1/brief.md and
-- docs/api/mcp-v1.md for the full contract):
--
--   * Owned by the caller (owner_uid), scoped to a Space (space_id) unless
--     the record is a platform-provided `system` MCP. `system` rows carry
--     NULL space_id and are visible across every Space.
--   * Rich content (tags, tools, examples, faqs, notes, connection config)
--     is stored as JSON columns because v1 does not search inside them and
--     the payload is naturally schemaless per MCP. If a later slice needs
--     to filter/rank on tool names or FAQ content, promote the relevant
--     collection to its own table then.
--   * Soft delete via deleted_at so we can restore or debug without hard
--     losing user content. All read paths must filter deleted_at IS NULL.
--   * Character set utf8mb4 so emoji icons (🐙, 🧩, …) and CJK content
--     round-trip correctly.
--   * No secret values are ever persisted. The application layer strips
--     token-like env / header values before insert; see docs/api/mcp-v1.md
--     §5 for the redaction rules.
--
-- Uniqueness -----------------------------------------------------------------
-- We want (owner_uid, space_id, name) to be unique among LIVE rows so a user
-- cannot publish two MCPs named "GitHub MCP" in the same Space.
--
-- SUPERSEDED APPROACH (do not implement): an earlier design enforced this in
-- the service layer with `SELECT ... FOR UPDATE` inside the create/rename txn.
-- A concurrency integration test (internal/repository/mcp_test.go,
-- TestConcurrentCreateSameName) proved that recipe DEADLOCKS under MySQL 8
-- (InnoDB Error 1213): a `SELECT ... FOR UPDATE` on a *non-existent*
-- (owner_uid, space_id, name) row takes a shared gap/next-key lock, so N
-- concurrent creators all acquire it and then race to upgrade to an
-- insert-intention lock — a circular wait — instead of one winning and the
-- rest getting name_taken.
--
-- CURRENT APPROACH: a real DB-level UNIQUE constraint, added in
-- migrations/sql/20260714-02-mcp-uniqueness.sql. MySQL 8 has no partial
-- (`WHERE deleted_at IS NULL`) unique index, so a STORED generated column
-- `name_live = IF(deleted_at IS NULL, name, NULL)` carries the live name, and
-- a UNIQUE index over (owner_uid, space_id, name_live) enforces the rule:
--   * a second LIVE row with the same tuple fails with duplicate-key
--     (Error 1062), which the repository maps to err.marketplace.mcp.name_taken
--     — no pre-SELECT, no gap lock, no deadlock;
--   * a soft-deleted row has name_live = NULL, and MySQL unique indexes permit
--     many NULLs, so the name is free to reuse after delete;
--   * `system` rows (space_id NULL) do not constrain each other — matching the
--     prior <=> NULL-safe behavior; system rows are not created via the public
--     API in v1.
-- See 20260714-02-mcp-uniqueness.sql for the DDL and rationale.
--
-- Future indexes -------------------------------------------------------------
-- The mine-page path uses `idx_owner_created` and filters `category` in a
-- second pass (filesort). Fine at v1 scale (a single user tends to own <
-- ~200 MCPs). If the mine + category combination starts feeling slow, add:
--   CREATE INDEX idx_owner_cat_created
--       ON mcp_servers (owner_uid, category, created_at);
-- and drop it from any list path that no longer needs the composite.
-- Same story for keyword search over `name` / `slogan`: v1 is a full scan;
-- promote to `FULLTEXT (name, slogan)` or a sidecar index once a Space
-- crosses ~10 k live MCPs.
-- ============================================================================

-- +migrate StatementBegin
CREATE TABLE IF NOT EXISTS `mcp_servers` (
  -- Identifier: ULID-style opaque string generated by the service. 26 chars
  -- gives us monotonic sortable IDs without leaking a numeric row count.
  `id`                  VARCHAR(64)  NOT NULL,

  -- User-facing basics. name is required; slogan is a short pitch used on
  -- the market card.
  `name`                VARCHAR(128) NOT NULL,
  `slogan`              VARCHAR(512) NOT NULL DEFAULT '',
  `category`            VARCHAR(64)  NOT NULL,

  -- Icon: emoji, short label, or an inline `data:` image URL (base64).
  -- MEDIUMTEXT gives us headroom for a modestly-sized PNG data URL without
  -- forcing a separate object store this quarter.
  `icon`                MEDIUMTEXT   NOT NULL,

  -- JSON collections. Each column has a strict shape defined by the API
  -- doc; the server normalizes on write (trim, dedupe, drop empties).
  `tags_json`           JSON         NOT NULL,
  `tools_json`          JSON         NOT NULL,
  `usage_examples_json` JSON         NOT NULL,
  `faqs_json`           JSON         NOT NULL,
  `notes_json`          JSON         NOT NULL,

  -- Visibility scope: enforced by the service layer, not the DB, but
  -- constrained here so an unexpected value is impossible.
  --   public  — visible to every member of `space_id`
  --   private — visible only to `owner_uid` in `space_id`
  --   system  — visible from every Space; `space_id` is NULL
  `visibility`          ENUM('public','private','system') NOT NULL DEFAULT 'private',

  -- Ownership + tenancy.
  --   owner_uid   — always populated (server-stamped from Octo token).
  --   space_id    — populated for public/private; NULL for system.
  --   creator_name — snapshot of Identity.name at create time; not renamed
  --                  when the underlying user later changes their nickname.
  `owner_uid`           VARCHAR(64)  NOT NULL,
  `space_id`            VARCHAR(64)  NULL,
  `creator_name`        VARCHAR(128) NOT NULL DEFAULT '',

  -- Connection.
  --   transport   — one of the three MCP transports.
  --   config_json — {url|command|args|env|headers|authType|serverName}.
  --                 Never contains secret values (see redaction rules).
  `transport`           ENUM('stdio','streamable-http','sse') NOT NULL,
  `config_json`         JSON         NOT NULL,

  -- Timestamps. Milliseconds so ULID ordering stays informative on the
  -- API surface as well.
  `created_at`          DATETIME(3)  NOT NULL,
  `updated_at`          DATETIME(3)  NOT NULL,
  `deleted_at`          DATETIME(3)  NULL DEFAULT NULL,

  PRIMARY KEY (`id`),

  -- Primary list-page query: visibility + space + category, newest first.
  -- Covers GET /mcps for public/private/system in one path (system rows
  -- have space_id NULL, which is treated as a distinct bucket by MySQL).
  KEY `idx_scope_cat_created`
      (`visibility`, `space_id`, `category`, `created_at`),

  -- Owner-first path for GET /mcps/mine and permission checks on mutation.
  KEY `idx_owner_created`
      (`owner_uid`, `created_at`),

  -- Soft-delete sweep + admin queries.
  KEY `idx_deleted_at` (`deleted_at`)
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'MCP catalog entries (mcp-catalog-v1)';
-- +migrate StatementEnd

-- +migrate Down
DROP TABLE IF EXISTS `mcp_servers`;
